install.packages('themis')
install.packages('randomForest')
install.packages('readxl')
install.packages('rpart')
install.packages('vip')
install.packages('parsnip')
install.packages('rsample')
install.packages('workflows')
install.packages("lifecycle")
install.packages('yardstick')
install.packages("C50", repos="http://R-Forge.R-project.org") 
install.packages("ranger")
install.packages('yardstick')
install.packages('tune')
install.packages("tibble")
install.packages("plotly")
install.packages("C5.0")
install.packages("lightgbm")
install.packages('recipes')
install.packages("xgboost")
install.packages("bench")
install.packages("rpart.plot")
install.packages("gbm")
install.packages("viridis")



